# Generated by Django 5.1.2 on 2024-11-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField()),
                ('report_type', models.CharField(max_length=50)),
                ('report_content', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
