# Generated by Django 5.1.3 on 2024-12-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_event_time_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=8, null=True),
        ),
    ]
