# Generated by Django 5.1.3 on 2024-12-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_alter_event_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
